// <auto-generated />
namespace MvcSoporteCF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TelefonoFechaEmpleado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TelefonoFechaEmpleado));
        
        string IMigrationMetadata.Id
        {
            get { return "201912031639232_TelefonoFechaEmpleado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
